apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-goof-deployment
  labels:
    app: java-goof
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-goof
  template:
    metadata:
      labels:
        app: java-goof
    spec:
      containers:
      - name: java-goof
        image: omearaj/java-goof
        ports:
        - containerPort: 8080
