version: 2.1 #

orbs:
  snyk: snyk/snyk@0.0.8
  
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-demo-java-spring # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      #- restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      #    key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      #- run: mvn dependency:go-offline # gets the project dependencies
      
      #- save_cache: # saves the project dependencies
      #    paths:
      #      - ~/.m2
      #    key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
     # - snyk/scan:
     #    fail-on-issues: false
     #    monitor-on-build: true
     #    project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app'
     #    severity-threshold: high
     #    token-variable: SNYK_TOKEN
      
      - run: mvn install
